// ─── SETORES MOCK DATA ────────────────────────────────────────────────────────
// Estrutura pronta para substituir por chamadas reais à API.
// Exemplo de integração:
//   const { data } = await api.get('/setores')  →  substitui SETORES_MOCK
//   await api.post('/setores', payload)          →  em handleSave (novo)
//   await api.put(`/setores/${id}`, payload)     →  em handleSave (editar)
//   await api.delete(`/setores/${id}`)           →  em handleDelete

export const SETORES_MOCK = [
  {
    id: "SET-001",
    nome: "Área de Produção",
    responsavel: "Eng. Carlos Meier",
    acesso: "restrito",   // "liberado" | "restrito" | "bloqueado"
    status: "ativo",      // "ativo" | "restrito" | "inativo"
    visitantes: 6,
    fluxo: 18,
    epiObrig: true,
    ultimaAtualizacao: { data: "29/07", hora: "11h42" },
  },
  {
    id: "SET-002",
    nome: "Laboratório de Qual.",
    responsavel: "Dra. Fernanda Lopes",
    acesso: "restrito",
    status: "ativo",
    visitantes: 4,
    fluxo: 11,
    epiObrig: true,
    ultimaAtualizacao: { data: "29/07", hora: "09h15" },
  },
  {
    id: "SET-003",
    nome: "Almoxarifado",
    responsavel: "Sup. Marcos Dias",
    acesso: "liberado",
    status: "ativo",
    visitantes: 3,
    fluxo: 8,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "08h30" },
  },
  {
    id: "SET-004",
    nome: "Administração",
    responsavel: "Coord. Ana Beatriz",
    acesso: "liberado",
    status: "ativo",
    visitantes: 7,
    fluxo: 14,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "10h05" },
  },
  {
    id: "SET-005",
    nome: "Câmara Fria",
    responsavel: "Téc. Bruno Assis",
    acesso: "restrito",
    status: "restrito",
    visitantes: 1,
    fluxo: 3,
    epiObrig: true,
    ultimaAtualizacao: { data: "29/07", hora: "17h00" },
  },
  {
    id: "SET-006",
    nome: "Manutenção Geral",
    responsavel: "Mec. Roberto Pires",
    acesso: "liberado",
    status: "ativo",
    visitantes: 2,
    fluxo: 6,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "07h55" },
  },
  {
    id: "SET-007",
    nome: "Refeitório",
    responsavel: "Coord. Julia Ramos",
    acesso: "liberado",
    status: "ativo",
    visitantes: 5,
    fluxo: 10,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "12h01" },
  },
  {
    id: "SET-008",
    nome: "Portaria Principal",
    responsavel: "Ag. Rafael Silva",
    acesso: "liberado",
    status: "ativo",
    visitantes: 9,
    fluxo: 38,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "11h59" },
  },
  {
    id: "SET-009",
    nome: "Controle de Qualidade",
    responsavel: "Téc. Mariana Costa",
    acesso: "restrito",
    status: "ativo",
    visitantes: 2,
    fluxo: 5,
    epiObrig: true,
    ultimaAtualizacao: { data: "29/07", hora: "14h22" },
  },
  {
    id: "SET-010",
    nome: "Expedição",
    responsavel: "Op. Leandro Faria",
    acesso: "liberado",
    status: "ativo",
    visitantes: 4,
    fluxo: 9,
    epiObrig: false,
    ultimaAtualizacao: { data: "29/07", hora: "15h10" },
  },
  {
    id: "SET-011",
    nome: "Vestiário / Higien.",
    responsavel: "Sup. Carla Nunes",
    acesso: "liberado",
    status: "ativo",
    visitantes: 0,
    fluxo: 4,
    epiObrig: false,
    ultimaAtualizacao: { data: "28/07", hora: "18h00" },
  },
  {
    id: "SET-012",
    nome: "Sala de Servidores",
    responsavel: "TI. Diego Moraes",
    acesso: "bloqueado",
    status: "inativo",
    visitantes: 0,
    fluxo: 0,
    epiObrig: false,
    ultimaAtualizacao: { data: "28/07", hora: "09h00" },
  },
];